run:
  timeout: 5m
  tests: false
  go: '1.24'

linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  revive:
    rules:
      - name: exported
        disabled: false
      - name: var-naming
        disabled: false
      - name: unexported-return
        disabled: false

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - revive

issues:
  exclude-dirs:
    - src/docs
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
