// Code generated by MockGen. DO NOT EDIT.
// Source: src/pkg/storage/localstack_s3.go
//
// Generated by this command:
//
//	mockgen -source=src/pkg/storage/localstack_s3.go -destination=src/tests/mocks/storage/storage_mock.go -package=mock_storage
//

// Package mock_storage is a generated GoMock package.
package mock_storage

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAvatarStorage is a mock of AvatarStorage interface.
type MockAvatarStorage struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarStorageMockRecorder
	isgomock struct{}
}

// MockAvatarStorageMockRecorder is the mock recorder for MockAvatarStorage.
type MockAvatarStorageMockRecorder struct {
	mock *MockAvatarStorage
}

// NewMockAvatarStorage creates a new mock instance.
func NewMockAvatarStorage(ctrl *gomock.Controller) *MockAvatarStorage {
	mock := &MockAvatarStorage{ctrl: ctrl}
	mock.recorder = &MockAvatarStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarStorage) EXPECT() *MockAvatarStorageMockRecorder {
	return m.recorder
}

// EnsureBucket mocks base method.
func (m *MockAvatarStorage) EnsureBucket(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureBucket", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureBucket indicates an expected call of EnsureBucket.
func (mr *MockAvatarStorageMockRecorder) EnsureBucket(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureBucket", reflect.TypeOf((*MockAvatarStorage)(nil).EnsureBucket), arg0)
}

// UploadAvatar mocks base method.
func (m *MockAvatarStorage) UploadAvatar(arg0 context.Context, arg1, arg2 string, arg3 []byte, arg4 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadAvatar", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadAvatar indicates an expected call of UploadAvatar.
func (mr *MockAvatarStorageMockRecorder) UploadAvatar(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAvatar", reflect.TypeOf((*MockAvatarStorage)(nil).UploadAvatar), arg0, arg1, arg2, arg3, arg4)
}
