// Code generated by MockGen. DO NOT EDIT.
// Source: src/pkg/mail/service.go
//
// Generated by this command:
//
//	mockgen -source=src/pkg/mail/service.go -destination=src/tests/mocks/mail/mailer_mock.go -package=mock_mail
//

// Package mock_mail is a generated GoMock package.
package mock_mail

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMailer is a mock of Mailer interface.
type MockMailer struct {
	ctrl     *gomock.Controller
	recorder *MockMailerMockRecorder
	isgomock struct{}
}

// MockMailerMockRecorder is the mock recorder for MockMailer.
type MockMailerMockRecorder struct {
	mock *MockMailer
}

// NewMockMailer creates a new mock instance.
func NewMockMailer(ctrl *gomock.Controller) *MockMailer {
	mock := &MockMailer{ctrl: ctrl}
	mock.recorder = &MockMailerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMailer) EXPECT() *MockMailerMockRecorder {
	return m.recorder
}

// SendEmailVerificationOTP mocks base method.
func (m *MockMailer) SendEmailVerificationOTP(arg0 context.Context, arg1, arg2, arg3 string, arg4 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmailVerificationOTP", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmailVerificationOTP indicates an expected call of SendEmailVerificationOTP.
func (mr *MockMailerMockRecorder) SendEmailVerificationOTP(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmailVerificationOTP", reflect.TypeOf((*MockMailer)(nil).SendEmailVerificationOTP), arg0, arg1, arg2, arg3, arg4)
}
