// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "emc_lb/src/pkg/entities"

	mock "github.com/stretchr/testify/mock"
)

// BrandCacheStore is an autogenerated mock type for the BrandCacheStore type
type BrandCacheStore struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx
func (_m *BrandCacheStore) GetAll(ctx context.Context) ([]entities.BrandResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []entities.BrandResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entities.BrandResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entities.BrandResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.BrandResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *BrandCacheStore) GetByID(ctx context.Context, id string) (entities.BrandResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 entities.BrandResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entities.BrandResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.BrandResponse); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entities.BrandResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Invalidate provides a mock function with given fields: ctx, id
func (_m *BrandCacheStore) Invalidate(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Invalidate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InvalidateAll provides a mock function with given fields: ctx
func (_m *BrandCacheStore) InvalidateAll(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetAll provides a mock function with given fields: ctx, brands
func (_m *BrandCacheStore) SetAll(ctx context.Context, brands []entities.BrandResponse) error {
	ret := _m.Called(ctx, brands)

	if len(ret) == 0 {
		panic("no return value specified for SetAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []entities.BrandResponse) error); ok {
		r0 = rf(ctx, brands)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetByID provides a mock function with given fields: ctx, id, brand
func (_m *BrandCacheStore) SetByID(ctx context.Context, id string, brand entities.BrandResponse) error {
	ret := _m.Called(ctx, id, brand)

	if len(ret) == 0 {
		panic("no return value specified for SetByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entities.BrandResponse) error); ok {
		r0 = rf(ctx, id, brand)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBrandCacheStore creates a new instance of BrandCacheStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBrandCacheStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *BrandCacheStore {
	mock := &BrandCacheStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
