// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "emc_lb/src/pkg/entities"

	mock "github.com/stretchr/testify/mock"
)

// CategoryCacheStore is an autogenerated mock type for the CategoryCacheStore type
type CategoryCacheStore struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx
func (_m *CategoryCacheStore) GetAll(ctx context.Context) ([]entities.CategoryResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []entities.CategoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entities.CategoryResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entities.CategoryResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.CategoryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *CategoryCacheStore) GetByID(ctx context.Context, id string) (entities.CategoryResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 entities.CategoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entities.CategoryResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.CategoryResponse); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entities.CategoryResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Invalidate provides a mock function with given fields: ctx, id
func (_m *CategoryCacheStore) Invalidate(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Invalidate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InvalidateAll provides a mock function with given fields: ctx
func (_m *CategoryCacheStore) InvalidateAll(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetAll provides a mock function with given fields: ctx, categories
func (_m *CategoryCacheStore) SetAll(ctx context.Context, categories []entities.CategoryResponse) error {
	ret := _m.Called(ctx, categories)

	if len(ret) == 0 {
		panic("no return value specified for SetAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []entities.CategoryResponse) error); ok {
		r0 = rf(ctx, categories)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetByID provides a mock function with given fields: ctx, id, category
func (_m *CategoryCacheStore) SetByID(ctx context.Context, id string, category entities.CategoryResponse) error {
	ret := _m.Called(ctx, id, category)

	if len(ret) == 0 {
		panic("no return value specified for SetByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entities.CategoryResponse) error); ok {
		r0 = rf(ctx, id, category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCategoryCacheStore creates a new instance of CategoryCacheStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryCacheStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryCacheStore {
	mock := &CategoryCacheStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
