// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "emc_lb/src/pkg/entities"

	mock "github.com/stretchr/testify/mock"
)

// CategoryCacheStore is an autogenerated mock type for the CategoryCacheStore type
type CategoryCacheStore struct {
	mock.Mock
}

// GetList provides a mock function with given fields: ctx
func (_m *CategoryCacheStore) GetList(ctx context.Context) ([]entities.CategoryResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetList")
	}

	var r0 []entities.CategoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entities.CategoryResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entities.CategoryResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.CategoryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InvalidateList provides a mock function with given fields: ctx
func (_m *CategoryCacheStore) InvalidateList(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetList provides a mock function with given fields: ctx, categories
func (_m *CategoryCacheStore) SetList(ctx context.Context, categories []entities.CategoryResponse) error {
	ret := _m.Called(ctx, categories)

	if len(ret) == 0 {
		panic("no return value specified for SetList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []entities.CategoryResponse) error); ok {
		r0 = rf(ctx, categories)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCategoryCacheStore creates a new instance of CategoryCacheStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryCacheStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryCacheStore {
	mock := &CategoryCacheStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
