// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "emc_lb/src/pkg/entities"

	mock "github.com/stretchr/testify/mock"
)

// CouponCacheStore is an autogenerated mock type for the CouponCacheStore type
type CouponCacheStore struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx
func (_m *CouponCacheStore) GetAll(ctx context.Context) ([]entities.CouponResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []entities.CouponResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entities.CouponResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entities.CouponResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.CouponResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByCode provides a mock function with given fields: ctx, code
func (_m *CouponCacheStore) GetByCode(ctx context.Context, code string) (entities.Coupon, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 entities.Coupon
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entities.Coupon, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.Coupon); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Get(0).(entities.Coupon)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InvalidateAll provides a mock function with given fields: ctx
func (_m *CouponCacheStore) InvalidateAll(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InvalidateByCode provides a mock function with given fields: ctx, code
func (_m *CouponCacheStore) InvalidateByCode(ctx context.Context, code string) error {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateByCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetAll provides a mock function with given fields: ctx, coupons
func (_m *CouponCacheStore) SetAll(ctx context.Context, coupons []entities.CouponResponse) error {
	ret := _m.Called(ctx, coupons)

	if len(ret) == 0 {
		panic("no return value specified for SetAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []entities.CouponResponse) error); ok {
		r0 = rf(ctx, coupons)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetByCode provides a mock function with given fields: ctx, code, coupon
func (_m *CouponCacheStore) SetByCode(ctx context.Context, code string, coupon entities.Coupon) error {
	ret := _m.Called(ctx, code, coupon)

	if len(ret) == 0 {
		panic("no return value specified for SetByCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entities.Coupon) error); ok {
		r0 = rf(ctx, code, coupon)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCouponCacheStore creates a new instance of CouponCacheStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCouponCacheStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *CouponCacheStore {
	mock := &CouponCacheStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
