// Code generated by MockGen. DO NOT EDIT.
// Source: src/pkg/cache/email_otp_store.go
//
// Generated by this command:
//
//	mockgen -source=src/pkg/cache/email_otp_store.go -destination=src/tests/mocks/cache/email_otp_mock.go -package=mock_cache
//

// Package mock_cache is a generated GoMock package.
package mock_cache

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockEmailOTPStore is a mock of EmailOTPStore interface.
type MockEmailOTPStore struct {
	ctrl     *gomock.Controller
	recorder *MockEmailOTPStoreMockRecorder
	isgomock struct{}
}

// MockEmailOTPStoreMockRecorder is the mock recorder for MockEmailOTPStore.
type MockEmailOTPStoreMockRecorder struct {
	mock *MockEmailOTPStore
}

// NewMockEmailOTPStore creates a new mock instance.
func NewMockEmailOTPStore(ctrl *gomock.Controller) *MockEmailOTPStore {
	mock := &MockEmailOTPStore{ctrl: ctrl}
	mock.recorder = &MockEmailOTPStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailOTPStore) EXPECT() *MockEmailOTPStoreMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockEmailOTPStore) Delete(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEmailOTPStoreMockRecorder) Delete(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEmailOTPStore)(nil).Delete), ctx, email)
}

// Get mocks base method.
func (m *MockEmailOTPStore) Get(ctx context.Context, email string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, email)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockEmailOTPStoreMockRecorder) Get(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockEmailOTPStore)(nil).Get), ctx, email)
}

// Save mocks base method.
func (m *MockEmailOTPStore) Save(ctx context.Context, email, otp string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, email, otp, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockEmailOTPStoreMockRecorder) Save(ctx, email, otp, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockEmailOTPStore)(nil).Save), ctx, email, otp, ttl)
}
