// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// EmailOTPStore is an autogenerated mock type for the EmailOTPStore type
type EmailOTPStore struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, email
func (_m *EmailOTPStore) Delete(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, email
func (_m *EmailOTPStore) Get(ctx context.Context, email string) (string, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, email, otp, ttl
func (_m *EmailOTPStore) Save(ctx context.Context, email string, otp string, ttl time.Duration) error {
	ret := _m.Called(ctx, email, otp, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = rf(ctx, email, otp, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEmailOTPStore creates a new instance of EmailOTPStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmailOTPStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmailOTPStore {
	mock := &EmailOTPStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
