// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "emc_lb/src/pkg/entities"

	mock "github.com/stretchr/testify/mock"
)

// ProductCacheStore is an autogenerated mock type for the ProductCacheStore type
type ProductCacheStore struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx
func (_m *ProductCacheStore) GetAll(ctx context.Context) ([]entities.ProductResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []entities.ProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entities.ProductResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entities.ProductResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.ProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ProductCacheStore) GetByID(ctx context.Context, id string) (entities.ProductResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 entities.ProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entities.ProductResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.ProductResponse); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entities.ProductResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Invalidate provides a mock function with given fields: ctx, id
func (_m *ProductCacheStore) Invalidate(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Invalidate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InvalidateAll provides a mock function with given fields: ctx
func (_m *ProductCacheStore) InvalidateAll(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetAll provides a mock function with given fields: ctx, products
func (_m *ProductCacheStore) SetAll(ctx context.Context, products []entities.ProductResponse) error {
	ret := _m.Called(ctx, products)

	if len(ret) == 0 {
		panic("no return value specified for SetAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []entities.ProductResponse) error); ok {
		r0 = rf(ctx, products)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetByID provides a mock function with given fields: ctx, id, product
func (_m *ProductCacheStore) SetByID(ctx context.Context, id string, product entities.ProductResponse) error {
	ret := _m.Called(ctx, id, product)

	if len(ret) == 0 {
		panic("no return value specified for SetByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entities.ProductResponse) error); ok {
		r0 = rf(ctx, id, product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProductCacheStore creates a new instance of ProductCacheStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductCacheStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductCacheStore {
	mock := &ProductCacheStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
