// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// RefreshTokenStore is an autogenerated mock type for the RefreshTokenStore type
type RefreshTokenStore struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, refreshToken
func (_m *RefreshTokenStore) Delete(ctx context.Context, refreshToken string) error {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserID provides a mock function with given fields: ctx, refreshToken
func (_m *RefreshTokenStore) GetUserID(ctx context.Context, refreshToken string) (string, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for GetUserID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, userID, refreshToken, ttl
func (_m *RefreshTokenStore) Save(ctx context.Context, userID string, refreshToken string, ttl time.Duration) error {
	ret := _m.Called(ctx, userID, refreshToken, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = rf(ctx, userID, refreshToken, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRefreshTokenStore creates a new instance of RefreshTokenStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshTokenStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshTokenStore {
	mock := &RefreshTokenStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
