// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "emc_lb/src/pkg/entities"

	mock "github.com/stretchr/testify/mock"
)

// ShopCacheStore is an autogenerated mock type for the ShopCacheStore type
type ShopCacheStore struct {
	mock.Mock
}

// GetByOwnerID provides a mock function with given fields: ctx, ownerID
func (_m *ShopCacheStore) GetByOwnerID(ctx context.Context, ownerID string) (entities.ShopResponse, error) {
	ret := _m.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for GetByOwnerID")
	}

	var r0 entities.ShopResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entities.ShopResponse, error)); ok {
		return rf(ctx, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.ShopResponse); ok {
		r0 = rf(ctx, ownerID)
	} else {
		r0 = ret.Get(0).(entities.ShopResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InvalidateByOwnerID provides a mock function with given fields: ctx, ownerID
func (_m *ShopCacheStore) InvalidateByOwnerID(ctx context.Context, ownerID string) error {
	ret := _m.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateByOwnerID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, ownerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetByOwnerID provides a mock function with given fields: ctx, ownerID, shop
func (_m *ShopCacheStore) SetByOwnerID(ctx context.Context, ownerID string, shop entities.ShopResponse) error {
	ret := _m.Called(ctx, ownerID, shop)

	if len(ret) == 0 {
		panic("no return value specified for SetByOwnerID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, entities.ShopResponse) error); ok {
		r0 = rf(ctx, ownerID, shop)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewShopCacheStore creates a new instance of ShopCacheStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShopCacheStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShopCacheStore {
	mock := &ShopCacheStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
