// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                  uuid.UUID      `json:"id"`
	Email               string         `json:"email"`
	Phone               *string        `json:"phone"`
	FullName            *string        `json:"full_name"`
	UserName            string         `json:"user_name"`
	PasswordHash        string         `json:"password_hash"`
	PasswordChangedAt   time.Time      `json:"password_changed_at"`
	EmailVerified       bool           `json:"email_verified"`
	EmailVerifiedAt     time.Time      `json:"email_verified_at"`
	PhoneVerified       bool           `json:"phone_verified"`
	PhoneVerifiedAt     time.Time      `json:"phone_verified_at"`
	AvatarUrl           *string        `json:"avatar_url"`
	Gender              *string        `json:"gender"`
	BirthDate           time.Time      `json:"birth_date"`
	Status              string         `json:"status"`
	IsBanned            bool           `json:"is_banned"`
	BannedReason        *string        `json:"banned_reason"`
	Role                string         `json:"role"`
	TotalOrders         int32          `json:"total_orders"`
	TotalSpent          pgtype.Numeric `json:"total_spent"`
	RewardPoints        int64          `json:"reward_points"`
	LastLoginAt         time.Time      `json:"last_login_at"`
	LastLoginIp         *netip.Addr    `json:"last_login_ip"`
	FailedLoginAttempts int32          `json:"failed_login_attempts"`
	LockedUntil         time.Time      `json:"locked_until"`
	LanguageCode        *string        `json:"language_code"`
	Timezone            *string        `json:"timezone"`
	IsDeleted           bool           `json:"is_deleted"`
	DeletedAt           time.Time      `json:"deleted_at"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
}
