// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmPaymentAtomic = `-- name: ConfirmPaymentAtomic :execrows
UPDATE orders
SET payment_status = $2, 
    status = $3, 
    payment_transaction_id = $4,
    updated_at = NOW()
WHERE invoice_number = $1 
  AND payment_status = 'unpaid' 
  AND status != 'cancelled'
  AND is_deleted = false
`

type ConfirmPaymentAtomicParams struct {
	InvoiceNumber        string  `json:"invoice_number"`
	PaymentStatus        string  `json:"payment_status"`
	Status               string  `json:"status"`
	PaymentTransactionID *string `json:"payment_transaction_id"`
}

func (q *Queries) ConfirmPaymentAtomic(ctx context.Context, arg ConfirmPaymentAtomicParams) (int64, error) {
	result, err := q.db.Exec(ctx, confirmPaymentAtomic,
		arg.InvoiceNumber,
		arg.PaymentStatus,
		arg.Status,
		arg.PaymentTransactionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    payment_group_id, shop_id, user_id, invoice_number, sub_total, 
    coupon_code, discount_amount, tax_amount, total_amount, 
    status, payment_status, payment_method, shipping_address, contact_phone
) VALUES (
    $1, $2, (SELECT id FROM users WHERE users.uuid = $3), $4, $5, 
    $6, $7, $8, $9, 
    $10, $11, $12, $13, $14
)
RETURNING id, uuid, payment_group_id, shop_id, user_id, invoice_number, sub_total, coupon_code, discount_amount, tax_amount, total_amount, status, payment_status, payment_method, payment_transaction_id, shipping_address, contact_phone, is_deleted, created_at, updated_at
`

type CreateOrderParams struct {
	PaymentGroupID  *string        `json:"payment_group_id"`
	ShopID          *string        `json:"shop_id"`
	Uuid            uuid.UUID      `json:"uuid"`
	InvoiceNumber   string         `json:"invoice_number"`
	SubTotal        pgtype.Numeric `json:"sub_total"`
	CouponCode      *string        `json:"coupon_code"`
	DiscountAmount  pgtype.Numeric `json:"discount_amount"`
	TaxAmount       pgtype.Numeric `json:"tax_amount"`
	TotalAmount     pgtype.Numeric `json:"total_amount"`
	Status          string         `json:"status"`
	PaymentStatus   string         `json:"payment_status"`
	PaymentMethod   *string        `json:"payment_method"`
	ShippingAddress *string        `json:"shipping_address"`
	ContactPhone    *string        `json:"contact_phone"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.PaymentGroupID,
		arg.ShopID,
		arg.Uuid,
		arg.InvoiceNumber,
		arg.SubTotal,
		arg.CouponCode,
		arg.DiscountAmount,
		arg.TaxAmount,
		arg.TotalAmount,
		arg.Status,
		arg.PaymentStatus,
		arg.PaymentMethod,
		arg.ShippingAddress,
		arg.ContactPhone,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.PaymentGroupID,
		&i.ShopID,
		&i.UserID,
		&i.InvoiceNumber,
		&i.SubTotal,
		&i.CouponCode,
		&i.DiscountAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.PaymentTransactionID,
		&i.ShippingAddress,
		&i.ContactPhone,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    order_id, product_id, product_name, sku, thumbnail, quantity, price, sub_total
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, uuid, order_id, product_id, product_name, sku, thumbnail, quantity, price, sub_total
`

type CreateOrderItemParams struct {
	OrderID     int64          `json:"order_id"`
	ProductID   string         `json:"product_id"`
	ProductName string         `json:"product_name"`
	Sku         *string        `json:"sku"`
	Thumbnail   *string        `json:"thumbnail"`
	Quantity    int32          `json:"quantity"`
	Price       pgtype.Numeric `json:"price"`
	SubTotal    pgtype.Numeric `json:"sub_total"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.ProductName,
		arg.Sku,
		arg.Thumbnail,
		arg.Quantity,
		arg.Price,
		arg.SubTotal,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.OrderID,
		&i.ProductID,
		&i.ProductName,
		&i.Sku,
		&i.Thumbnail,
		&i.Quantity,
		&i.Price,
		&i.SubTotal,
	)
	return i, err
}

const getOrderByInvoiceNumber = `-- name: GetOrderByInvoiceNumber :one
SELECT o.id, o.uuid, o.payment_group_id, o.shop_id, o.user_id, o.invoice_number, o.sub_total, o.coupon_code, o.discount_amount, o.tax_amount, o.total_amount, o.status, o.payment_status, o.payment_method, o.payment_transaction_id, o.shipping_address, o.contact_phone, o.is_deleted, o.created_at, o.updated_at, u.uuid as user_uuid 
FROM orders o
JOIN users u ON o.user_id = u.id
WHERE o.invoice_number = $1 AND o.is_deleted = false
`

type GetOrderByInvoiceNumberRow struct {
	ID                   int64          `json:"id"`
	Uuid                 uuid.UUID      `json:"uuid"`
	PaymentGroupID       *string        `json:"payment_group_id"`
	ShopID               *string        `json:"shop_id"`
	UserID               int64          `json:"user_id"`
	InvoiceNumber        string         `json:"invoice_number"`
	SubTotal             pgtype.Numeric `json:"sub_total"`
	CouponCode           *string        `json:"coupon_code"`
	DiscountAmount       pgtype.Numeric `json:"discount_amount"`
	TaxAmount            pgtype.Numeric `json:"tax_amount"`
	TotalAmount          pgtype.Numeric `json:"total_amount"`
	Status               string         `json:"status"`
	PaymentStatus        string         `json:"payment_status"`
	PaymentMethod        *string        `json:"payment_method"`
	PaymentTransactionID *string        `json:"payment_transaction_id"`
	ShippingAddress      *string        `json:"shipping_address"`
	ContactPhone         *string        `json:"contact_phone"`
	IsDeleted            bool           `json:"is_deleted"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	UserUuid             uuid.UUID      `json:"user_uuid"`
}

func (q *Queries) GetOrderByInvoiceNumber(ctx context.Context, invoiceNumber string) (GetOrderByInvoiceNumberRow, error) {
	row := q.db.QueryRow(ctx, getOrderByInvoiceNumber, invoiceNumber)
	var i GetOrderByInvoiceNumberRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.PaymentGroupID,
		&i.ShopID,
		&i.UserID,
		&i.InvoiceNumber,
		&i.SubTotal,
		&i.CouponCode,
		&i.DiscountAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.PaymentTransactionID,
		&i.ShippingAddress,
		&i.ContactPhone,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserUuid,
	)
	return i, err
}

const getOrderByUUID = `-- name: GetOrderByUUID :one
SELECT o.id, o.uuid, o.payment_group_id, o.shop_id, o.user_id, o.invoice_number, o.sub_total, o.coupon_code, o.discount_amount, o.tax_amount, o.total_amount, o.status, o.payment_status, o.payment_method, o.payment_transaction_id, o.shipping_address, o.contact_phone, o.is_deleted, o.created_at, o.updated_at, u.uuid as user_uuid 
FROM orders o
JOIN users u ON o.user_id = u.id
WHERE o.uuid = $1 AND o.is_deleted = false
`

type GetOrderByUUIDRow struct {
	ID                   int64          `json:"id"`
	Uuid                 uuid.UUID      `json:"uuid"`
	PaymentGroupID       *string        `json:"payment_group_id"`
	ShopID               *string        `json:"shop_id"`
	UserID               int64          `json:"user_id"`
	InvoiceNumber        string         `json:"invoice_number"`
	SubTotal             pgtype.Numeric `json:"sub_total"`
	CouponCode           *string        `json:"coupon_code"`
	DiscountAmount       pgtype.Numeric `json:"discount_amount"`
	TaxAmount            pgtype.Numeric `json:"tax_amount"`
	TotalAmount          pgtype.Numeric `json:"total_amount"`
	Status               string         `json:"status"`
	PaymentStatus        string         `json:"payment_status"`
	PaymentMethod        *string        `json:"payment_method"`
	PaymentTransactionID *string        `json:"payment_transaction_id"`
	ShippingAddress      *string        `json:"shipping_address"`
	ContactPhone         *string        `json:"contact_phone"`
	IsDeleted            bool           `json:"is_deleted"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	UserUuid             uuid.UUID      `json:"user_uuid"`
}

func (q *Queries) GetOrderByUUID(ctx context.Context, argUuid uuid.UUID) (GetOrderByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getOrderByUUID, argUuid)
	var i GetOrderByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.PaymentGroupID,
		&i.ShopID,
		&i.UserID,
		&i.InvoiceNumber,
		&i.SubTotal,
		&i.CouponCode,
		&i.DiscountAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.Status,
		&i.PaymentStatus,
		&i.PaymentMethod,
		&i.PaymentTransactionID,
		&i.ShippingAddress,
		&i.ContactPhone,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserUuid,
	)
	return i, err
}

const getOrderItemsByOrderID = `-- name: GetOrderItemsByOrderID :many
SELECT id, uuid, order_id, product_id, product_name, sku, thumbnail, quantity, price, sub_total FROM order_items 
WHERE order_id = $1
`

func (q *Queries) GetOrderItemsByOrderID(ctx context.Context, orderID int64) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, getOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.OrderID,
			&i.ProductID,
			&i.ProductName,
			&i.Sku,
			&i.Thumbnail,
			&i.Quantity,
			&i.Price,
			&i.SubTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllOrders = `-- name: ListAllOrders :many
SELECT id, uuid, payment_group_id, shop_id, user_id, invoice_number, sub_total, coupon_code, discount_amount, tax_amount, total_amount, status, payment_status, payment_method, payment_transaction_id, shipping_address, contact_phone, is_deleted, created_at, updated_at FROM orders 
WHERE is_deleted = false
ORDER BY created_at DESC
`

func (q *Queries) ListAllOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, listAllOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.PaymentGroupID,
			&i.ShopID,
			&i.UserID,
			&i.InvoiceNumber,
			&i.SubTotal,
			&i.CouponCode,
			&i.DiscountAmount,
			&i.TaxAmount,
			&i.TotalAmount,
			&i.Status,
			&i.PaymentStatus,
			&i.PaymentMethod,
			&i.PaymentTransactionID,
			&i.ShippingAddress,
			&i.ContactPhone,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUserID = `-- name: ListOrdersByUserID :many
SELECT id, uuid, payment_group_id, shop_id, user_id, invoice_number, sub_total, coupon_code, discount_amount, tax_amount, total_amount, status, payment_status, payment_method, payment_transaction_id, shipping_address, contact_phone, is_deleted, created_at, updated_at FROM orders 
WHERE user_id = (SELECT id FROM users WHERE users.uuid = $1) AND is_deleted = false
ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByUserID(ctx context.Context, argUuid uuid.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUserID, argUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.PaymentGroupID,
			&i.ShopID,
			&i.UserID,
			&i.InvoiceNumber,
			&i.SubTotal,
			&i.CouponCode,
			&i.DiscountAmount,
			&i.TaxAmount,
			&i.TotalAmount,
			&i.Status,
			&i.PaymentStatus,
			&i.PaymentMethod,
			&i.PaymentTransactionID,
			&i.ShippingAddress,
			&i.ContactPhone,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders 
SET status = $2 
WHERE uuid = $1 AND is_deleted = false
`

type UpdateOrderStatusParams struct {
	Uuid   uuid.UUID `json:"uuid"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.Uuid, arg.Status)
	return err
}

const updateOrderStatusAtomic = `-- name: UpdateOrderStatusAtomic :execrows
UPDATE orders
SET status = $3, updated_at = NOW()
WHERE uuid = $1 AND status = $2 AND is_deleted = false
`

type UpdateOrderStatusAtomicParams struct {
	Uuid     uuid.UUID `json:"uuid"`
	Status   string    `json:"status"`
	Status_2 string    `json:"status_2"`
}

func (q *Queries) UpdateOrderStatusAtomic(ctx context.Context, arg UpdateOrderStatusAtomicParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOrderStatusAtomic, arg.Uuid, arg.Status, arg.Status_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
