// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error
	CreateCustomerStats(ctx context.Context, userID int64) error
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) error
	GetAllRolePermissions(ctx context.Context) ([]GetAllRolePermissionsRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByUUID(ctx context.Context, argUuid uuid.UUID) (GetUserByUUIDRow, error)
	GetUserIDByUUID(ctx context.Context, argUuid uuid.UUID) (int64, error)
	GetUserProfileByUUID(ctx context.Context, argUuid uuid.UUID) (GetUserProfileByUUIDRow, error)
	LockUserAccount(ctx context.Context, arg LockUserAccountParams) error
	SoftDeleteUserByUUID(ctx context.Context, argUuid uuid.UUID) error
	UpdateFailedLoginAttempts(ctx context.Context, id int64) error
	UpdateUserAvatarByUUID(ctx context.Context, arg UpdateUserAvatarByUUIDParams) error
	UpdateUserLoginStats(ctx context.Context, arg UpdateUserLoginStatsParams) error
	VerifyUserEmail(ctx context.Context, email string) error
}

var _ Querier = (*Queries)(nil)
