// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetAllRolePermissions(ctx context.Context) ([]GetAllRolePermissionsRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserIDByID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	SoftDeleteUserByID(ctx context.Context, id uuid.UUID) error
	UpdateUserAvatarByEmail(ctx context.Context, arg UpdateUserAvatarByEmailParams) error
	UpdateUserAvatarByID(ctx context.Context, arg UpdateUserAvatarByIDParams) error
	VerifyUserEmail(ctx context.Context, email string) error
}

var _ Querier = (*Queries)(nil)
