// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserIDByID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	SoftDeleteUserByEmail(ctx context.Context, email string) error
	UpdateUserAvatarByEmail(ctx context.Context, arg UpdateUserAvatarByEmailParams) error
	UpdateUserAvatarByID(ctx context.Context, arg UpdateUserAvatarByIDParams) error
	VerifyUserEmail(ctx context.Context, email string) error
}

var _ Querier = (*Queries)(nil)
