// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rbac.sql

package sqlc

import (
	"context"
)

const assignPermissionToRole = `-- name: AssignPermissionToRole :exec
INSERT INTO role_permissions (role_code, permission_code)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignPermissionToRoleParams struct {
	RoleCode       string `json:"role_code"`
	PermissionCode string `json:"permission_code"`
}

func (q *Queries) AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error {
	_, err := q.db.Exec(ctx, assignPermissionToRole, arg.RoleCode, arg.PermissionCode)
	return err
}

const createPermission = `-- name: CreatePermission :one
INSERT INTO permissions (code, name, description)
VALUES ($1, $2, $3)
RETURNING code, name, description, created_at
`

type CreatePermissionParams struct {
	Code        string  `json:"code"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, createPermission, arg.Code, arg.Name, arg.Description)
	var i Permission
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (code, name, description)
VALUES ($1, $2, $3)
RETURNING code, name, description, created_at
`

type CreateRoleParams struct {
	Code        string  `json:"code"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Code, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getAllRolePermissions = `-- name: GetAllRolePermissions :many
SELECT r.code AS role_code, p.code AS permission_code
FROM roles r
JOIN role_permissions rp ON r.code = rp.role_code
JOIN permissions p ON rp.permission_code = p.code
`

type GetAllRolePermissionsRow struct {
	RoleCode       string `json:"role_code"`
	PermissionCode string `json:"permission_code"`
}

func (q *Queries) GetAllRolePermissions(ctx context.Context) ([]GetAllRolePermissionsRow, error) {
	rows, err := q.db.Query(ctx, getAllRolePermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllRolePermissionsRow{}
	for rows.Next() {
		var i GetAllRolePermissionsRow
		if err := rows.Scan(&i.RoleCode, &i.PermissionCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
