// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomerStats = `-- name: CreateCustomerStats :exec
INSERT INTO customer_stats (
    user_id
) VALUES (
    $1
)
`

func (q *Queries) CreateCustomerStats(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, createCustomerStats, userID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    password_hash,
    role,
    status,
    email_verified
) VALUES (
    $1, $2, 'customer', 'active', false
)
RETURNING id, uuid, email, created_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

type CreateUserRow struct {
	ID        int64     `json:"id"`
	Uuid      uuid.UUID `json:"uuid"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const createUserProfile = `-- name: CreateUserProfile :exec
INSERT INTO user_profiles (
    user_id,
    user_name,
    phone,
    phone_verified
) VALUES (
    $1, $2, $3, false
)
`

type CreateUserProfileParams struct {
	UserID   int64   `json:"user_id"`
	UserName *string `json:"user_name"`
	Phone    *string `json:"phone"`
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) error {
	_, err := q.db.Exec(ctx, createUserProfile, arg.UserID, arg.UserName, arg.Phone)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    uuid,
    email,
    password_hash,
    email_verified,
    role,
    status,
    is_banned,
    COALESCE(locked_until, '0001-01-01 00:00:00Z'::timestamptz) AS locked_until,
    failed_login_attempts
FROM users
WHERE email = $1 AND is_deleted = false
LIMIT 1
`

type GetUserByEmailRow struct {
	ID                  int64     `json:"id"`
	Uuid                uuid.UUID `json:"uuid"`
	Email               string    `json:"email"`
	PasswordHash        string    `json:"password_hash"`
	EmailVerified       bool      `json:"email_verified"`
	Role                string    `json:"role"`
	Status              string    `json:"status"`
	IsBanned            bool      `json:"is_banned"`
	LockedUntil         time.Time `json:"locked_until"`
	FailedLoginAttempts int32     `json:"failed_login_attempts"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Role,
		&i.Status,
		&i.IsBanned,
		&i.LockedUntil,
		&i.FailedLoginAttempts,
	)
	return i, err
}

const getUserByUUID = `-- name: GetUserByUUID :one
SELECT
    id,
    uuid,
    email,
    password_hash,
    email_verified,
    role
FROM users
WHERE uuid = $1 AND is_deleted = false
LIMIT 1
`

type GetUserByUUIDRow struct {
	ID            int64     `json:"id"`
	Uuid          uuid.UUID `json:"uuid"`
	Email         string    `json:"email"`
	PasswordHash  string    `json:"password_hash"`
	EmailVerified bool      `json:"email_verified"`
	Role          string    `json:"role"`
}

func (q *Queries) GetUserByUUID(ctx context.Context, argUuid uuid.UUID) (GetUserByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByUUID, argUuid)
	var i GetUserByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Role,
	)
	return i, err
}

const getUserIDByUUID = `-- name: GetUserIDByUUID :one
SELECT id
FROM users
WHERE uuid = $1 AND is_deleted = false
LIMIT 1
`

func (q *Queries) GetUserIDByUUID(ctx context.Context, argUuid uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getUserIDByUUID, argUuid)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUserProfileByUUID = `-- name: GetUserProfileByUUID :one
SELECT
    u.uuid,
    u.email,
    p.user_name,
    p.full_name,
    p.phone,
    p.avatar_url,
    u.role,
    u.status,
    u.email_verified,
    u.created_at,
    cs.total_orders,
    cs.total_spent,
    cs.reward_points
FROM users u
JOIN user_profiles p ON u.id = p.user_id
JOIN customer_stats cs ON u.id = cs.user_id
WHERE u.uuid = $1 AND u.is_deleted = false
LIMIT 1
`

type GetUserProfileByUUIDRow struct {
	Uuid          uuid.UUID      `json:"uuid"`
	Email         string         `json:"email"`
	UserName      *string        `json:"user_name"`
	FullName      *string        `json:"full_name"`
	Phone         *string        `json:"phone"`
	AvatarUrl     *string        `json:"avatar_url"`
	Role          string         `json:"role"`
	Status        string         `json:"status"`
	EmailVerified bool           `json:"email_verified"`
	CreatedAt     time.Time      `json:"created_at"`
	TotalOrders   int32          `json:"total_orders"`
	TotalSpent    pgtype.Numeric `json:"total_spent"`
	RewardPoints  int32          `json:"reward_points"`
}

func (q *Queries) GetUserProfileByUUID(ctx context.Context, argUuid uuid.UUID) (GetUserProfileByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getUserProfileByUUID, argUuid)
	var i GetUserProfileByUUIDRow
	err := row.Scan(
		&i.Uuid,
		&i.Email,
		&i.UserName,
		&i.FullName,
		&i.Phone,
		&i.AvatarUrl,
		&i.Role,
		&i.Status,
		&i.EmailVerified,
		&i.CreatedAt,
		&i.TotalOrders,
		&i.TotalSpent,
		&i.RewardPoints,
	)
	return i, err
}

const lockUserAccount = `-- name: LockUserAccount :exec
UPDATE users
SET
    locked_until = $2
WHERE id = $1 AND is_deleted = false
`

type LockUserAccountParams struct {
	ID          int64     `json:"id"`
	LockedUntil time.Time `json:"locked_until"`
}

func (q *Queries) LockUserAccount(ctx context.Context, arg LockUserAccountParams) error {
	_, err := q.db.Exec(ctx, lockUserAccount, arg.ID, arg.LockedUntil)
	return err
}

const softDeleteUserByUUID = `-- name: SoftDeleteUserByUUID :exec
UPDATE users
SET
    is_deleted = true,
    deleted_at = NOW(),
    updated_at = NOW()
WHERE uuid = $1 AND is_deleted = false
`

func (q *Queries) SoftDeleteUserByUUID(ctx context.Context, argUuid uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUserByUUID, argUuid)
	return err
}

const updateFailedLoginAttempts = `-- name: UpdateFailedLoginAttempts :exec
UPDATE users
SET
    failed_login_attempts = failed_login_attempts + 1
WHERE id = $1 AND is_deleted = false
`

func (q *Queries) UpdateFailedLoginAttempts(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateFailedLoginAttempts, id)
	return err
}

const updateUserAvatarByUUID = `-- name: UpdateUserAvatarByUUID :exec
UPDATE user_profiles
SET
    avatar_url = $2
WHERE user_id = (SELECT id FROM users WHERE uuid = $1 AND is_deleted = false)
`

type UpdateUserAvatarByUUIDParams struct {
	Uuid      uuid.UUID `json:"uuid"`
	AvatarUrl *string   `json:"avatar_url"`
}

func (q *Queries) UpdateUserAvatarByUUID(ctx context.Context, arg UpdateUserAvatarByUUIDParams) error {
	_, err := q.db.Exec(ctx, updateUserAvatarByUUID, arg.Uuid, arg.AvatarUrl)
	return err
}

const updateUserLoginStats = `-- name: UpdateUserLoginStats :exec
UPDATE users
SET
    failed_login_attempts = 0,
    last_login_at = NOW(),
    last_login_ip = $2
WHERE id = $1 AND is_deleted = false
`

type UpdateUserLoginStatsParams struct {
	ID          int64   `json:"id"`
	LastLoginIp *string `json:"last_login_ip"`
}

func (q *Queries) UpdateUserLoginStats(ctx context.Context, arg UpdateUserLoginStatsParams) error {
	_, err := q.db.Exec(ctx, updateUserLoginStats, arg.ID, arg.LastLoginIp)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET
    password_hash = $2,
    password_changed_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND is_deleted = false
`

type UpdateUserPasswordParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
UPDATE users
SET
    email_verified = true,
    email_verified_at = NOW(),
    updated_at = NOW()
WHERE email = $1 AND is_deleted = false
`

func (q *Queries) VerifyUserEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, verifyUserEmail, email)
	return err
}
