// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    email,
    password_hash,
    user_name,
    phone,
    role,
    status,
    email_verified,
    phone_verified
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    'customer',
    'active',
    false,
    false
)
RETURNING id, email, user_name, phone, created_at
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	UserName     string    `json:"user_name"`
	Phone        *string   `json:"phone"`
}

type CreateUserRow struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	UserName  string    `json:"user_name"`
	Phone     *string   `json:"phone"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.UserName,
		arg.Phone,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.UserName,
		&i.Phone,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    email,
    password_hash,
    email_verified,
    role
FROM users
WHERE email = $1 AND is_deleted = false
LIMIT 1
`

type GetUserByEmailRow struct {
	ID            uuid.UUID `json:"id"`
	Email         string    `json:"email"`
	PasswordHash  string    `json:"password_hash"`
	EmailVerified bool      `json:"email_verified"`
	Role          string    `json:"role"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Role,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    email,
    password_hash,
    email_verified,
    role
FROM users
WHERE id = $1 AND is_deleted = false
LIMIT 1
`

type GetUserByIDRow struct {
	ID            uuid.UUID `json:"id"`
	Email         string    `json:"email"`
	PasswordHash  string    `json:"password_hash"`
	EmailVerified bool      `json:"email_verified"`
	Role          string    `json:"role"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Role,
	)
	return i, err
}

const getUserIDByID = `-- name: GetUserIDByID :one
SELECT id
FROM users
WHERE id = $1 AND is_deleted = false
LIMIT 1
`

func (q *Queries) GetUserIDByID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIDByID, id)
	err := row.Scan(&id)
	return id, err
}

const softDeleteUserByID = `-- name: SoftDeleteUserByID :exec
UPDATE users
SET
    is_deleted = true,
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND is_deleted = false
`

func (q *Queries) SoftDeleteUserByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUserByID, id)
	return err
}

const updateUserAvatarByEmail = `-- name: UpdateUserAvatarByEmail :exec
UPDATE users
SET
    avatar_url = $2,
    updated_at = NOW()
WHERE email = $1 AND is_deleted = false
`

type UpdateUserAvatarByEmailParams struct {
	Email     string  `json:"email"`
	AvatarUrl *string `json:"avatar_url"`
}

func (q *Queries) UpdateUserAvatarByEmail(ctx context.Context, arg UpdateUserAvatarByEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserAvatarByEmail, arg.Email, arg.AvatarUrl)
	return err
}

const updateUserAvatarByID = `-- name: UpdateUserAvatarByID :exec
UPDATE users
SET
    avatar_url = $2,
    updated_at = NOW()
WHERE id = $1 AND is_deleted = false
`

type UpdateUserAvatarByIDParams struct {
	ID        uuid.UUID `json:"id"`
	AvatarUrl *string   `json:"avatar_url"`
}

func (q *Queries) UpdateUserAvatarByID(ctx context.Context, arg UpdateUserAvatarByIDParams) error {
	_, err := q.db.Exec(ctx, updateUserAvatarByID, arg.ID, arg.AvatarUrl)
	return err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
UPDATE users
SET
    email_verified = true,
    email_verified_at = NOW(),
    updated_at = NOW()
WHERE email = $1
`

func (q *Queries) VerifyUserEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, verifyUserEmail, email)
	return err
}
