global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'emc_lb_api'
    static_configs:
      - targets: 
        - 'emc_api_node_1:8080'
        - 'emc_api_node_2:8080'
        - 'emc_api_node_3:8080'
