// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "emc_lb/src/pkg/entities"

	mock "github.com/stretchr/testify/mock"
)

// CartRepository is an autogenerated mock type for the CartRepository type
type CartRepository struct {
	mock.Mock
}

// ClearCart provides a mock function with given fields: ctx, userID
func (_m *CartRepository) ClearCart(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ClearCart")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EnsureIndexes provides a mock function with given fields: ctx
func (_m *CartRepository) EnsureIndexes(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for EnsureIndexes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *CartRepository) GetByUserID(ctx context.Context, userID string) (entities.Cart, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 entities.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entities.Cart, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.Cart); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(entities.Cart)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveItems provides a mock function with given fields: ctx, userID, productIDs
func (_m *CartRepository) RemoveItems(ctx context.Context, userID string, productIDs []string) error {
	ret := _m.Called(ctx, userID, productIDs)

	if len(ret) == 0 {
		panic("no return value specified for RemoveItems")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, userID, productIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: ctx, cart
func (_m *CartRepository) Save(ctx context.Context, cart entities.Cart) (entities.Cart, error) {
	ret := _m.Called(ctx, cart)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 entities.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Cart) (entities.Cart, error)); ok {
		return rf(ctx, cart)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.Cart) entities.Cart); ok {
		r0 = rf(ctx, cart)
	} else {
		r0 = ret.Get(0).(entities.Cart)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.Cart) error); ok {
		r1 = rf(ctx, cart)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCartRepository creates a new instance of CartRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCartRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CartRepository {
	mock := &CartRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
