// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "emc_lb/src/pkg/entities"

	mock "github.com/stretchr/testify/mock"
)

// CouponRepository is an autogenerated mock type for the CouponRepository type
type CouponRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, coupon
func (_m *CouponRepository) Create(ctx context.Context, coupon entities.Coupon) (entities.Coupon, error) {
	ret := _m.Called(ctx, coupon)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entities.Coupon
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Coupon) (entities.Coupon, error)); ok {
		return rf(ctx, coupon)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.Coupon) entities.Coupon); ok {
		r0 = rf(ctx, coupon)
	} else {
		r0 = ret.Get(0).(entities.Coupon)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.Coupon) error); ok {
		r1 = rf(ctx, coupon)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByCode provides a mock function with given fields: ctx, code
func (_m *CouponRepository) GetByCode(ctx context.Context, code string) (entities.Coupon, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 entities.Coupon
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entities.Coupon, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.Coupon); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Get(0).(entities.Coupon)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *CouponRepository) GetByID(ctx context.Context, id string) (entities.Coupon, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 entities.Coupon
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entities.Coupon, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.Coupon); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entities.Coupon)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IncrementUsage provides a mock function with given fields: ctx, code, count
func (_m *CouponRepository) IncrementUsage(ctx context.Context, code string, count int64) error {
	ret := _m.Called(ctx, code, count)

	if len(ret) == 0 {
		panic("no return value specified for IncrementUsage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = rf(ctx, code, count)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx
func (_m *CouponRepository) List(ctx context.Context) ([]entities.Coupon, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []entities.Coupon
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entities.Coupon, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entities.Coupon); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Coupon)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, update
func (_m *CouponRepository) Update(ctx context.Context, id string, update map[string]interface{}) (entities.Coupon, error) {
	ret := _m.Called(ctx, id, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 entities.Coupon
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) (entities.Coupon, error)); ok {
		return rf(ctx, id, update)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) entities.Coupon); ok {
		r0 = rf(ctx, id, update)
	} else {
		r0 = ret.Get(0).(entities.Coupon)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]interface{}) error); ok {
		r1 = rf(ctx, id, update)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateAndIncrementUsage provides a mock function with given fields: ctx, code, orderAmount
func (_m *CouponRepository) ValidateAndIncrementUsage(ctx context.Context, code string, orderAmount float64) (entities.Coupon, error) {
	ret := _m.Called(ctx, code, orderAmount)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAndIncrementUsage")
	}

	var r0 entities.Coupon
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, float64) (entities.Coupon, error)); ok {
		return rf(ctx, code, orderAmount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, float64) entities.Coupon); ok {
		r0 = rf(ctx, code, orderAmount)
	} else {
		r0 = ret.Get(0).(entities.Coupon)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, float64) error); ok {
		r1 = rf(ctx, code, orderAmount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCouponRepository creates a new instance of CouponRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCouponRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CouponRepository {
	mock := &CouponRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
