// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "emc_lb/src/pkg/entities"

	meilisearch "github.com/meilisearch/meilisearch-go"

	mock "github.com/stretchr/testify/mock"
)

// ProductSearchRepository is an autogenerated mock type for the ProductSearchRepository type
type ProductSearchRepository struct {
	mock.Mock
}

// IndexProduct provides a mock function with given fields: ctx, product
func (_m *ProductSearchRepository) IndexProduct(ctx context.Context, product entities.Product) error {
	ret := _m.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for IndexProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Product) error); ok {
		r0 = rf(ctx, product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InitIndex provides a mock function with given fields: ctx
func (_m *ProductSearchRepository) InitIndex(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InitIndex")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveProduct provides a mock function with given fields: ctx, id
func (_m *ProductSearchRepository) RemoveProduct(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RemoveProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Search provides a mock function with given fields: ctx, query, limit, offset
func (_m *ProductSearchRepository) Search(ctx context.Context, query string, limit int64, offset int64) (*meilisearch.SearchResponse, error) {
	ret := _m.Called(ctx, query, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *meilisearch.SearchResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) (*meilisearch.SearchResponse, error)); ok {
		return rf(ctx, query, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) *meilisearch.SearchResponse); ok {
		r0 = rf(ctx, query, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*meilisearch.SearchResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64) error); ok {
		r1 = rf(ctx, query, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProductSearchRepository creates a new instance of ProductSearchRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductSearchRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductSearchRepository {
	mock := &ProductSearchRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
