// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "emc_lb/src/pkg/entities"

	mock "github.com/stretchr/testify/mock"
)

// ShopRepository is an autogenerated mock type for the ShopRepository type
type ShopRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, shop
func (_m *ShopRepository) Create(ctx context.Context, shop entities.Shop) (entities.Shop, error) {
	ret := _m.Called(ctx, shop)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 entities.Shop
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Shop) (entities.Shop, error)); ok {
		return rf(ctx, shop)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.Shop) entities.Shop); ok {
		r0 = rf(ctx, shop)
	} else {
		r0 = ret.Get(0).(entities.Shop)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.Shop) error); ok {
		r1 = rf(ctx, shop)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ShopRepository) GetByID(ctx context.Context, id string) (entities.Shop, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 entities.Shop
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entities.Shop, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.Shop); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(entities.Shop)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByOwnerID provides a mock function with given fields: ctx, ownerID
func (_m *ShopRepository) GetByOwnerID(ctx context.Context, ownerID string) (entities.Shop, error) {
	ret := _m.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for GetByOwnerID")
	}

	var r0 entities.Shop
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entities.Shop, error)); ok {
		return rf(ctx, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entities.Shop); ok {
		r0 = rf(ctx, ownerID)
	} else {
		r0 = ret.Get(0).(entities.Shop)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, update
func (_m *ShopRepository) Update(ctx context.Context, id string, update map[string]interface{}) (entities.Shop, error) {
	ret := _m.Called(ctx, id, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 entities.Shop
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) (entities.Shop, error)); ok {
		return rf(ctx, id, update)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) entities.Shop); ok {
		r0 = rf(ctx, id, update)
	} else {
		r0 = ret.Get(0).(entities.Shop)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]interface{}) error); ok {
		r1 = rf(ctx, id, update)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewShopRepository creates a new instance of ShopRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShopRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShopRepository {
	mock := &ShopRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
