// Code generated by MockGen. DO NOT EDIT.
// Source: src/internal/repository/user_repository.go
//
// Generated by this command:
//
//	mockgen -source=src/internal/repository/user_repository.go -destination=src/tests/mocks/repository/user_repository_mock.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	sqlc "emc_lb/src/internal/db/sqlc"
	entities "emc_lb/src/pkg/entities"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(arg0 context.Context, arg1 entities.User) (entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), arg0, arg1)
}

// GetByEmail mocks base method.
func (m *MockUserRepository) GetByEmail(arg0 context.Context, arg1 string) (entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", arg0, arg1)
	ret0, _ := ret[0].(entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepositoryMockRecorder) GetByEmail(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepository)(nil).GetByEmail), arg0, arg1)
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(arg0 context.Context, arg1 uuid.UUID) (entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), arg0, arg1)
}

// GetIDByID mocks base method.
func (m *MockUserRepository) GetIDByID(arg0 context.Context, arg1 uuid.UUID) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDByID", arg0, arg1)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIDByID indicates an expected call of GetIDByID.
func (mr *MockUserRepositoryMockRecorder) GetIDByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDByID", reflect.TypeOf((*MockUserRepository)(nil).GetIDByID), arg0, arg1)
}

// GetUserProfileByID mocks base method.
func (m *MockUserRepository) GetUserProfileByID(arg0 context.Context, arg1 uuid.UUID) (sqlc.GetUserProfileByIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProfileByID", arg0, arg1)
	ret0, _ := ret[0].(sqlc.GetUserProfileByIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProfileByID indicates an expected call of GetUserProfileByID.
func (mr *MockUserRepositoryMockRecorder) GetUserProfileByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProfileByID", reflect.TypeOf((*MockUserRepository)(nil).GetUserProfileByID), arg0, arg1)
}

// LockUserAccount mocks base method.
func (m *MockUserRepository) LockUserAccount(arg0 context.Context, arg1 sqlc.LockUserAccountParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockUserAccount", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// LockUserAccount indicates an expected call of LockUserAccount.
func (mr *MockUserRepositoryMockRecorder) LockUserAccount(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockUserAccount", reflect.TypeOf((*MockUserRepository)(nil).LockUserAccount), arg0, arg1)
}

// SoftDeleteByID mocks base method.
func (m *MockUserRepository) SoftDeleteByID(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteByID", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteByID indicates an expected call of SoftDeleteByID.
func (mr *MockUserRepositoryMockRecorder) SoftDeleteByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteByID", reflect.TypeOf((*MockUserRepository)(nil).SoftDeleteByID), arg0, arg1)
}

// UpdateAvatarByID mocks base method.
func (m *MockUserRepository) UpdateAvatarByID(arg0 context.Context, arg1 uuid.UUID, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvatarByID", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAvatarByID indicates an expected call of UpdateAvatarByID.
func (mr *MockUserRepositoryMockRecorder) UpdateAvatarByID(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvatarByID", reflect.TypeOf((*MockUserRepository)(nil).UpdateAvatarByID), arg0, arg1, arg2)
}

// UpdateFailedLoginAttempts mocks base method.
func (m *MockUserRepository) UpdateFailedLoginAttempts(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFailedLoginAttempts", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFailedLoginAttempts indicates an expected call of UpdateFailedLoginAttempts.
func (mr *MockUserRepositoryMockRecorder) UpdateFailedLoginAttempts(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFailedLoginAttempts", reflect.TypeOf((*MockUserRepository)(nil).UpdateFailedLoginAttempts), arg0, arg1)
}

// UpdateUserLoginStats mocks base method.
func (m *MockUserRepository) UpdateUserLoginStats(arg0 context.Context, arg1 sqlc.UpdateUserLoginStatsParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserLoginStats", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserLoginStats indicates an expected call of UpdateUserLoginStats.
func (mr *MockUserRepositoryMockRecorder) UpdateUserLoginStats(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserLoginStats", reflect.TypeOf((*MockUserRepository)(nil).UpdateUserLoginStats), arg0, arg1)
}

// VerifyEmail mocks base method.
func (m *MockUserRepository) VerifyEmail(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyEmail", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyEmail indicates an expected call of VerifyEmail.
func (mr *MockUserRepositoryMockRecorder) VerifyEmail(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyEmail", reflect.TypeOf((*MockUserRepository)(nil).VerifyEmail), arg0, arg1)
}
